### ISSUE TITLE
Something wrong in training own data

### ISSUE THREAD

**Issue by RichardHWD** [luuuyi/RefineDet.PyTorch#10]
It is a the best pytorch version implement ! But I change to detect only 1 class, it tell me :
copy_if failed to synchronize: device-side assert triggered
That means calsses index wrong.

I have change VOC_CLASSES = ('rebar',), It wrongs
I have change VOC_CLASSES = ('__background__', 'rebar'), It wrongs
I have change all params about class size into 2.

And I wonder :
why It happens, 
why there is no backgroud index in you project?

Thank you all the time.

**Comment by luuuyi** [comment]
@RichardHWD maybe you can read this #3

**Comment by rw1995** [comment]
I meet the same problem ,could you tell me how to solve it??i havechange VOC_CLASSES = [('aircraft')),but it don't work=-=,could you help me?
![cp](https://user-images.githubusercontent.com/37976371/58002420-e567f780-7b10-11e9-91cf-923ed2dcd6ce.png)

**Comment by Areslala** [comment]
I also meet the same problem,have you solved it?thank you!

**Comment by cxzhou95** [comment]
Same problem.

Maybe there is a bug when the classes =2 (1 foreground category + 1background).

I also try another own datasets classes = 6, no errors.
