### ISSUE TITLE
Where do you use confidence_threshold when test?

### ISSUE THREAD

**Issue by RichardHWD** [luuuyi/RefineDet.PyTorch#11]
It is one of the best RefineDet project implement in pytoch ! Thank you so much!
But when I evaluate the model , I can not find that confidence_threshold and top_k are used in somewhere , and I can not measure the model in different threshold and top_k value.
How to fix them ?
How dose the code calculate the map when you does`t use the confidence_threshold and top_k ?

**Comment by luuuyi** [comment]
you can see here https://github.com/luuuyi/RefineDet.PyTorch/blob/0e4b24ce07245fcb8c48292326a731729cc5746a/layers/functions/detection.py#L7-L22

**Comment by luuuyi** [comment]
@RichardHWD
