### ISSUE TITLE
test images meet many problems

### ISSUE THREAD

**Issue by lixiandea** [luuuyi/RefineDet.PyTorch#16]
is anyone meet some problem about training your model with your own data?
when i train the model, nothing goes wrong, but when i use my model to detect objects, i got an answer with all zeros,can and nothing goes wrong but i cant test my model on cuda()

**Comment by luuuyi** [comment]
@lixiandea maybe somewhere is wrong, you can check your code. If you use the demo.py, that might be wrong because the demo.py is origin version of ssd.pytorch. You should change it yourself, it's very easy.
