### ISSUE TITLE
Question about the extra layers

### ISSUE THREAD

**Issue by Fighting-JJ** [luuuyi/RefineDet.PyTorch#17]

**Comment by luuuyi** [comment]
@Fighting-JJ you should review code mor carefully.

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ you should review code mor carefully.

@luuuyi  Thank you for your reply.
Another Question :   layers += [nn.Conv2d(in_channels, v, kernel_size=(1, 3)[flag])]
Can you tell me the meaning of [flag] atfer the kernel_size ?  
I have searched times , but do not get what I want, and still confused about it.  Thanks a lot !!!

**Comment by luuuyi** [comment]
@Fighting-JJ this is basic use of python. When I input `a = (1,2)[flag]`, if flag == True, a = 2; Otherwise, flag == False, a = 1.

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ this is basic use of python. When I input `a = (1,2)[flag]`, if flag == True, a = 2; Otherwise, flag == False, a = 1.

Alright, I got it . Just work like list[index].
Thank you.
