### ISSUE TITLE
Train loss might be nan

### ISSUE THREAD

**Issue by Fighting-JJ** [luuuyi/RefineDet.PyTorch#18]
![图片](https://user-images.githubusercontent.com/17001854/56862286-e9a26880-69db-11e9-8b6d-3f752e1524ac.png)

Sometimes it works well, but can also get stuck in condition like the picture shows.

**Comment by luuuyi** [comment]
@Fighting-JJ yes, the ssd.pytorch repo has this problem, I aslo encounter this problem, but failed to solve it completely

**Comment by Fighting-JJ** [comment]
Another question about the  # Hard Negative Mining process  @luuuyi 

https://github.com/luuuyi/RefineDet.PyTorch/blob/0e4b24ce07245fcb8c48292326a731729cc5746a/layers/modules/refinedet_multibox_loss.py#L124-L132

after  sort loss_idx, Can you get the top-k Negtive samples of  larger loss? 
I think the `neg` you get is just randomly chosen from all negtive samples in the  `loss_c`

if you are assure the correctness of the process, maybe i should review the code more carefully again.
Thank you.

**Comment by luuuyi** [comment]
@Fighting-JJ Actually, it takes top-K negative samples.

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ Actually, it takes top-K negative samples.

Allright. Tahnks for your reply.

**Comment by Fighting-JJ** [comment]
Another Question or suggestion.  
VGG-Source setting  ` vgg_source = [21, 28, -2]` in the function : arm_multibox  odm_multibox   only works for net-modle without BN-layers.

**Comment by Fighting-JJ** [comment]
It takes almost 29 hours to train the RefineDet-512 on Pascal Data with 2 1080TI GPUS.
And Get the mAP:
![图片](https://user-images.githubusercontent.com/17001854/56896307-eda6b700-6abd-11e9-9968-43bd08294ea2.png)

**Comment by Fighting-JJ** [comment]
@luuuyi  老哥，加个微信，讨论学习一下。最近想修改为2分类，遇到些问题，请教一下。
我微信ID： lovezed6300
谢谢了。
其他想一起交流学习的，也可以加我一起学习。

**Comment by pengfeidip** [comment]
@Fighting-JJ 你的RefineDet-512 效果感觉一般啊，现在有什么进展吗？

**Comment by Fighting-JJ** [comment]
> @Fighting-JJ 你的RefineDet-512 效果感觉一般啊，现在有什么进展吗？

什么效果一般？二分类需要修改代码，还没动手搞。跑coco之类的数据，这份代码还可以

**Comment by pengfeidip** [comment]
> > @Fighting-JJ 你的RefineDet-512 效果感觉一般啊，现在有什么进展吗？
> 
> 什么效果一般？二分类需要修改代码，还没动手搞。跑coco之类的数据，这份代码还可以


好吧。现在你还在用这份代码吗？你是怎么解决在512尺度的nan问题的？通过降低学习率吗？

**Comment by jimeffry** [comment]
> It takes almost 29 hours to train the RefineDet-512 on Pascal Data with 2 1080TI GPUS.
> And Get the mAP:
> ![图片](https://user-images.githubusercontent.com/17001854/56896307-eda6b700-6abd-11e9-9968-43bd08294ea2.png)

In my opinion， you have a very great result. But when I am running the codes with 512-size, it could not convergence. Could you share the training preocess? Thank you!

**Comment by Fighting-JJ** [comment]
> > It takes almost 29 hours to train the RefineDet-512 on Pascal Data with 2 1080TI GPUS.
> > And Get the mAP:
> > ![图片](https://user-images.githubusercontent.com/17001854/56896307-eda6b700-6abd-11e9-9968-43bd08294ea2.png)
> 
> In my opinion， you have a very great result. But when I am running the codes with 512-size, it could not convergence. Could you share the training preocess? Thank you!

I almost forgot the  the training preocess. 
if loss nan happens ,you can just stop the training process, then restart it. 
you can run the train command times untill there is now loss nan, then you may succeed.

**Comment by jimeffry** [comment]
@Fighting-JJ 
  Thanks for your reply.
