### ISSUE TITLE
why the mAP on VOC2007 only 69.71%

### ISSUE THREAD

**Issue by lzcdawang** [luuuyi/RefineDet.PyTorch#2]
I only chang the num_work to 0

**Comment by luuuyi** [comment]
You should train on Pascal voc 2007and 2012

**Comment by wait1988** [comment]
@luuuyi I use train_refinedet320.sh to train voc0712 and test on voc07 and get "Mean AP = 0.7254".It's much worse than your reported result.

**Comment by luuuyi** [comment]
you can check if you modify somewhere, the result is trained on the origin repo setting.@wait1988
