### ISSUE TITLE
sorry,something wrong i don't know how to solve it

### ISSUE THREAD

**Issue by rw1995** [luuuyi/RefineDet.PyTorch#20]
![图片](https://user-images.githubusercontent.com/37976371/57978613-aae45900-7a43-11e9-975a-d20c4949686f.png)
=-=please what happen,thx to you

**Comment by rw1995** [comment]
i only follow your suggestion put the weight into weights and  do the sh

**Comment by luuuyi** [comment]
@rw1995 I can not get any more infomation with this pic, but I wonder know whether you have multi-gpu in your machine.

**Comment by rw1995** [comment]
i only have one GPU，i don't know why=-= @luuuyi 
when it train on voc2007, itis ok, but in my dataset ,it don't work

**Comment by luuuyi** [comment]
@rw1995 when you just have one gpu, you should set gpu_num equal to 1, i noticed that your error info mentions nn.DataParallel, you do not need to use it when you just have one gpu.
