### ISSUE TITLE
python eval_refinedet.py 时出现一下问题不知道怎么回事请楼主给予解答

### ISSUE THREAD

**Issue by zhangqiang12345678** [luuuyi/RefineDet.PyTorch#22]
Evaluating detections
Writing noise VOC results file
Writing nova VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "eval_refinedet.py", line 444, in <module>
    thresh=args.confidence_threshold)
  File "eval_refinedet.py", line 419, in test_net
    evaluate_detections(all_boxes, output_dir, dataset)
  File "eval_refinedet.py", line 424, in evaluate_detections
    do_python_eval(output_dir)
  File "eval_refinedet.py", line 177, in do_python_eval
    ovthresh=0.5, use_07_metric=use_07_metric)
  File "eval_refinedet.py", line 288, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '0c8fbc9601a1fa4533e46b19bd276d80'

**Comment by luuuyi** [comment]
@zhangqiang12345678 从报错上来看是字典的key找不到，你可以在中间过程调试一下看看

**Comment by zhangqiang12345678** [comment]
按照网上大家给出的思路，删掉了上一次训练遗留的cache，然后出现以下问题
obj_struct['pose'] = obj.find('pose').text

AttributeError: 'NoneType' object has no attribute 'text'
作者说根据xml来修改eval _refinedet.py中的语句。
博主能给点建议吗

**Comment by luuuyi** [comment]
@zhangqiang12345678 这是很基本的Python报错，跟算法没关系，你应该多调试一下。
