### ISSUE TITLE
关于COCO数据集的测试

### ISSUE THREAD

**Issue by Rodecin** [luuuyi/RefineDet.PyTorch#27]
想请问下博主是不是还没有对COCO数据集进行测试这部分功能。我没有找到对应的代码。
还有想问下COCO2014.sh脚本中trainval35k的数据集的生成是直接把train2014和val2014文件夹中的图片全部拷贝进trainval35k文件夹的吗？那测试COCO要在哪个数据集上进行呢？

**Comment by luuuyi** [comment]
@Rodecin 这部分我并没有集成去测试，你可以参考ssd.pytorch那个库改一下
