### ISSUE TITLE
coco

### ISSUE THREAD

**Issue by luyaozhi** [luuuyi/RefineDet.PyTorch#31]
when i train on coco ,i find that ,
loading annotations into memory...
Done (t=4.95s)
creating index...
index created!
ERROR: You specified size 300. However, currently only RefineDet320 and RefineDet512 is supported!
None
Loading base network...
Traceback (most recent call last):
  File "train_refinedetorg.py", line 288, in <module>
    train()
  File "train_refinedetorg.py", line 111, in train
    refinedet_net.vgg.load_state_dict(vgg_weights)
AttributeError: 'NoneType' object has no attribute 'vgg'

can u help me ?

**Comment by luuuyi** [comment]
@luuuyi you see, the logs said currently only RefineDet320 and RefineDet512 is supported, if you set size as 300, it won't create a object named refinedet_net, so this object has no attribute 'vgg'

**Comment by andyhahaha** [comment]
Hi luyaozhi,
Can you successfully train on coco and reach the paper accuracy? (refinedet 320 VGG: 29.4)
Can you provide the coco evaluation code? I want to train coco myself but I can't run evaluation. Thanks!
