### ISSUE TITLE
About Upsampling Conv kernel size

### ISSUE THREAD

**Issue by timho102003** [luuuyi/RefineDet.PyTorch#4]
The paper shows that the upsampling layer kernel is 4x4; however, ur upsampling layer is 2x2
Please correct me if I'm wrong, thanks a lot!!!
`feature_upsample_layers += [nn.ConvTranspose2d(256, 256, kernel_size=2, stride=2)]`

**Comment by luuuyi** [comment]
@timho102003 OK, I notice this problem, but I implement this work depend on the official repo(Caffe), the kernel size in Deconv is same to the author's work. That means maybe the author draw a wrong figure in paper.
But I think 2x2 or 4x4 is not a big problem in RefineDet, you can try.

**Comment by timho102003** [comment]
@luuuyi Thanks for ur prompt attention!
