### ISSUE TITLE
Memory Requirement

### ISSUE THREAD

**Issue by 0fine0** [luuuyi/RefineDet.PyTorch#42]
how much GPU memory will cost when batch size is 1

**Comment by immarioo** [comment]
i trained my datasets with refinedet512 in my rtx 2080Ti, i set the batchsize = 12 and it costs 10680MiB, about 10G GPU memory.

**Comment by 0fine0** [comment]
> i trained my datasets with refinedet512 in my rtx 2080Ti, i set the batchsize = 12 and it costs 10680MiB, about 10G GPU memory.

thanks a lot
